Added Readme
ROUNDS-Preservation/RoundsModdingTools pull request #3
Opened 2024-03-07 17:32 UTC by AALUND13

- Added Readme
- Rewrite Setup Symlink file

2024-03-07 21:58 UTC, Tess-y requested changes
Honestly, I disagree with the sim-link idea in the first place and would have rejected it if I had had the branch protection setup correctly before you had committed it to main. That being said. If you _really_ want to implement it that way, you must do so in a way that can function on all systems, not just windows. Otherwise I am considering reverting the change made to the csproj file.

2024-03-07 22:00 UTC, Scyye commented
I dont see a need for a symlink file.
Is that not just making it so ya dont have to change a single variable in the csproj files, which takes ~10 seconds?

2024-03-07 22:01 UTC, Tess-y commented
To my knowledge, that is the reason it is there. Which is why if it was a PR it would have been rejected.

2024-03-07 22:15 UTC, AALUND13 commented
Since I don't want to figure out how to recreate the same setup in a shell file, I may remove the need for it to be a symlink and rewrite the README, excluding any references to the symlink. The changes will be made within a few minutes to a few hours.

2024-03-07 23:10 UTC, AALUND13 commented
I can use Python to create a symlink that works on Windows, Linux/UNIX, and macOS. However, the end user must have Python installed on their system. What do you think about using python to create symlink?

2024-03-07 23:14 UTC, Scyye commented
I dont see a reason for it.
Its fixing a non-issue, and having a weird requirement of python in order to develop a ROUNDS mod, is quite unnecessary

2024-03-07 23:18 UTC, Tess-y commented
I agree, you are attempting to needlessly complicate what was as simple as changing a single variable in a single file.

2024-03-07 23:20 UTC, Tess-y commented
if you can come up with a system that allows any user to do this without the need of installing additional external tools, then by all means go for it. but barring that I will be rejecting this pull request, and reverting the change that you made to the project file.

2024-03-07 23:25 UTC, AALUND13 commented
I am against using Python cause you have to install a extra software just to run one file

2024-03-07 23:30 UTC, Tess-y commented
> I am against using Python cause you have to install a extra software just to run one file

you are quite literally the one who suggested using python the first place. what was the point of suggesting it if you are against it?

2024-03-07 23:48 UTC, AALUND13 commented
I just removed the need for a symlink and rewritten the readme cause to a complex of a non-issue just to solve one miner non-issue only save a few seconds at the end

2024-03-07 23:50 UTC, Scyye approved these changes

2024-03-08 20:08 UTC, Tess-y commented on README.md
> +- Replace `F:\SteamLibrary` with the path to your Steam Library folder.
Change lines 11 and 12 to just say to set the SteamFolder variable, rather then explicitly referencing _my_ Steam Library.
then I'll accept the PR.

2024-03-08 22:39 UTC, Tess-y approved these changes

2024-03-08 22:39 UTC, merged